### ISSUE TITLE
 could not find function "as.named.vector"

### ISSUE THREAD

**Issue by johndharrison** [vertesy/RoxygenReady#12]
This is a useful premise for a package. Running on a sample script I find:

Error in rr_extract_default_args(funnames[i]) : 
  could not find function "as.named.vector"

Looking in another repo I see: https://github.com/vertesy/TheCorvinas/blob/master/R/CodeAndRoll.R#L186

```
as.named.vector <- function(df_col, WhichDimNames = 1) { # Convert a dataframe column or row into a vector, keeping the corresponding dimension name.
    # use RowNames: WhichDimNames = 1 , 2: use ColNames
    # !!! might require drop=F in subsetting!!! eg: df_col[,3, drop=F]
    # df_col[which(unlist(lapply(df_col, is.null)))] = "NULL" # replace NULLs - they would fall out of vectors - DOES not work yet
    namez = dimnames(df_col)[[WhichDimNames]]
    if (is.list(df_col) & !is.data.frame(df_col)) {namez = names(df_col)}
    vecc = as.vector(unlist (df_col))
    names (vecc)= namez
    return (vecc)
}
```

Sourcing the above function allows the code to run without error.

**Comment by vertesy** [comment]
Thank you for notifying me, especially for the very precise description! 
Best,
Abel
