### ISSUE TITLE
rr_extract_all_functions_from_a_script expects `<-`

### ISSUE THREAD

**Issue by jmi5** [vertesy/RoxygenReady#13]
Although I know it's not the coding standard, I use `=` for assignment in R, and this includes function defintion. I see that rr_extract_all_functions_from_a_script is grepping as follows:
`patt = " *<- *function *\\(.+"`
`index = grep(patt, ScriptAsStringsPerLine, perl = T)`

This results in RoxygenReady not detecting any functions in my script.

**Comment by vertesy** [comment]
Good point, "=" is discouraged nevertheless valid syntax. Will be fixed soon!

I think the same is true for `rr_extract_all_descriptions_from_comment()`

### I need to fix:
- [x] https://github.com/vertesy/RoxygenReady/blob/master/RoxygenReady/R/RoxygenReady.R#L116
- [x] https://github.com/vertesy/RoxygenReady/blob/master/RoxygenReady/R/RoxygenReady.R#L148

**Comment by vertesy** [comment]
### I think this solves it

```
ScriptAsStringsPerLine = rbind("sa \n\n","asas \n toClipboard  =function(x, sep=, header=FALSE, row.names=FALSE, col.names =F) { # Copy an R-object to your clipboard on OS X.")
# ScriptAsStringsPerLine = "asas \n toClipboard  =function(x, sep=, header=FALSE, row.names=FALSE, col.names =F) { # Copy an R-object to your clipboard on OS X."

patt1 = " *<-|= *function *\\(.+"

index = grep(patt1, ScriptAsStringsPerLine, perl = T); index
```

**Comment by jmi5** [comment]
Thanks!
