### ISSUE TITLE
object '        FUN' not found

### ISSUE THREAD

**Issue by Wolfffff** [vertesy/RoxygenReady#15]
Constantly getting Error in FUN(X[[i]], ...) : object '        FUN' not found in almost all files.

**Comment by vertesy** [comment]
Hey, thx for reaching out, can you give [some more detail,](https://stackoverflow.com/help/minimal-reproducible-example) what you did?

**Comment by vertesy** [comment]
I just followed the instructions, starting from scratch and it works fine for me.

**Comment by Wolfffff** [comment]
I did as well -- on trying more, it only breaks on some files. For example, trying to run it on https://github.com/Wolfffff/RATrak/blob/master/R/processing.R gives this issue.

**Comment by vertesy** [comment]
Hey, I am sorry but won't have time to troubleshoot your files. By quick look, that script does not meet the expected formatting: `RoxygenReady expects a short description in the first line, after the `{` character, which will be parsed into the description field of the function annotation.` >> See homepage
