### ISSUE TITLE
Edit the project's own website to redirect to vertesy/RoxygenReady

### ISSUE THREAD

**Issue by vertesy** [vertesy/RoxygenReady#8]
### change the following links
- [x] view on github 
- [x] maintained by
- [x] edit the website?
### edit:

```
   subl /Users/abelvertesy/roxygenready.github.io/index.html
```

**Comment by roxygenready** [comment]
Weird, although I can replace the link in the index.html, the site does not change it (after commit).

**Comment by vertesy** [comment]
Solved, only line 24 in index.html should be changed
